name: Scheduled Script Execution

on:
  schedule:
    - cron: '0 * * * *'  # Запуск щогодини. Ви можете змінити cron для потрібного вам часу.
  workflow_dispatch:  # Додає можливість запускати вручну з GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Залежно від версії Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Додайте інші залежності, якщо вони потрібні

    - name: Run the script
      run: |
        python warning_mailing_script.py  # Використовуйте відносний шлях до скрипта в кореневій директорії
